"""Standalone CETONI neMESYS syringe-pump integration.

The public API uses microlitres (uL) for volume and microlitres per minute
(uL/min) for flow.  The CETONI bus is not opened until :meth:`connect` is
called, so importing this module is safe on computers without the SDK or pump.
"""

from __future__ import annotations

import math
from pathlib import Path
import sys
import time
from typing import Any


DEFAULT_CONFIGURATION_PATH = Path(
    r"C:\Users\Public\Documents\QmixElements\Projects\default_project\Configurations\single"
)
DEFAULT_SDK_PYTHON_PATH = Path(r"C:\Users\Ola\AppData\Local\CETONI_SDK\lib\python")


class NemesysPumpError(RuntimeError):
    """Raised when a pump operation cannot be performed safely."""


class NemesysPump:
    """Control one CETONI neMESYS pump from a Qmix configuration.

    The pump is selected by its zero-based device index. This avoids coupling
    application code to names generated by a particular Qmix configuration.

    Positive continuous flow dispenses; negative continuous flow aspirates.
    Position commands always take a positive flow-rate magnitude because the
    target position determines the direction.
    """

    def __init__(
        self,
        configuration_path: str | Path = DEFAULT_CONFIGURATION_PATH,
        *,
        pump_index: int = 0,
        sdk_python_path: str | Path = DEFAULT_SDK_PYTHON_PATH,
        poll_interval_s: float = 0.1,
    ) -> None:
        self.configuration_path = Path(configuration_path)
        self.pump_index = int(pump_index)
        self.sdk_python_path = Path(sdk_python_path)
        self.poll_interval_s = self._positive_number(poll_interval_s, "poll_interval_s")

        if self.pump_index < 0:
            raise ValueError("pump_index must be zero or greater")

        self._qmixbus: Any = None
        self._qmixpump: Any = None
        self._bus: Any = None
        self._pump: Any = None
        self._bus_opened = False
        self._bus_started = False

    @property
    def is_connected(self) -> bool:
        """Whether this instance has an open, started bus and selected pump."""
        return self._bus_opened and self._bus_started and self._pump is not None

    def connect(self) -> None:
        """Open the CETONI bus, select this pump, and enable its drive.

        The startup sequence follows CETONI's required ordering: open the bus,
        look up the pump, start the bus, clear its fault state, then enable it.
        """
        if self.is_connected:
            return
        if not self.configuration_path.is_dir():
            raise NemesysPumpError(
                f"Qmix configuration directory does not exist: {self.configuration_path}"
            )

        self._load_sdk()
        self._bus = self._qmixbus.Bus()
        try:
            self._bus.open(str(self.configuration_path), 0)
            self._bus_opened = True

            self._pump = self._qmixpump.Pump()
            self._pump.lookup_by_device_index(self.pump_index)

            self._bus.start()
            self._bus_started = True

            self._pump.clear_fault()
            if self._pump.is_in_fault_state():
                raise NemesysPumpError(
                    "The neMESYS pump is still faulted after LCP_ClearFault"
                )
            if not self._pump.is_enabled():
                self._pump.enable(True)

            self._pump.set_volume_unit(
                self._qmixbus.UnitPrefix.micro,
                self._qmixpump.VolumeUnit.litres,
            )
            self._pump.set_flow_unit(
                self._qmixbus.UnitPrefix.micro,
                self._qmixpump.VolumeUnit.litres,
                self._qmixbus.TimeUnit.per_minute,
            )
        except Exception as exc:
            cleanup_errors = self._cleanup_bus(stop_pump=False)
            message = f"Could not connect to neMESYS pump: {exc}"
            if cleanup_errors:
                message += f"; cleanup also failed: {'; '.join(cleanup_errors)}"
            raise NemesysPumpError(message) from exc

    def configure_syringe(
        self,
        inner_diameter_mm: float,
        piston_stroke_mm: float,
    ) -> tuple[float, float]:
        """Set syringe geometry and return the geometry read back from the pump."""
        pump = self._ready_pump()
        diameter = self._positive_number(inner_diameter_mm, "inner_diameter_mm")
        stroke = self._positive_number(piston_stroke_mm, "piston_stroke_mm")
        pump.set_syringe_param(diameter, stroke)
        syringe = pump.get_syringe_param()
        return float(syringe.inner_diameter_mm), float(syringe.max_piston_stroke_mm)

    def reference_move(self, timeout_s: float = 60.0) -> None:
        """Reference the pump axis and wait until calibration finishes."""
        pump = self._ready_pump()
        timeout = self._positive_number(timeout_s, "timeout_s")
        pump.calibrate()
        self._wait_until_idle_or(
            pump.is_calibration_finished,
            timeout,
            "Reference move timed out",
        )

    def refill(self, flow_rate_ul_min: float) -> None:
        """Move to the syringe's maximum fill level at the requested speed."""
        self.move_to_volume(self.maximum_volume_ul, flow_rate_ul_min)

    def empty(self, flow_rate_ul_min: float) -> None:
        """Move to zero fill level at the requested speed."""
        self.move_to_volume(0.0, flow_rate_ul_min)

    def set_flow(self, flow_rate_ul_min: float) -> None:
        """Generate continuous flow; positive dispenses and negative aspirates.

        A value of zero stops the pump.
        """
        pump = self._ready_pump()
        flow = self._finite_number(flow_rate_ul_min, "flow_rate_ul_min")
        if flow == 0:
            pump.stop_pumping()
            return
        self._validate_flow_magnitude(abs(flow))
        pump.generate_flow(flow)

    def move_to_volume(self, volume_ul: float, flow_rate_ul_min: float) -> None:
        """Move to an absolute syringe fill volume at a specified flow rate."""
        pump = self._ready_pump()
        volume = self._finite_number(volume_ul, "volume_ul")
        flow = self._positive_number(flow_rate_ul_min, "flow_rate_ul_min")
        maximum = self.maximum_volume_ul
        if not 0.0 <= volume <= maximum:
            raise ValueError(f"volume_ul must be between 0 and {maximum:g} uL")
        self._validate_flow_magnitude(flow)
        pump.set_fill_level(volume, flow)

    def stop(self) -> None:
        """Stop the selected pump immediately."""
        self._ready_pump().stop_pumping()

    @property
    def current_volume_ul(self) -> float:
        return float(self._ready_pump().get_fill_level())

    @property
    def current_flow_ul_min(self) -> float:
        return float(self._ready_pump().get_flow_is())

    @property
    def maximum_volume_ul(self) -> float:
        return float(self._ready_pump().get_volume_max())

    @property
    def maximum_flow_ul_min(self) -> float:
        return float(self._ready_pump().get_flow_rate_max())

    @property
    def is_pumping(self) -> bool:
        return bool(self._ready_pump().is_pumping())

    @property
    def syringe_parameters(self) -> tuple[float, float]:
        """Return ``(inner_diameter_mm, piston_stroke_mm)``."""
        syringe = self._ready_pump().get_syringe_param()
        return float(syringe.inner_diameter_mm), float(syringe.max_piston_stroke_mm)

    @property
    def device_name(self) -> str:
        pump = self._ready_pump()
        getter = getattr(pump, "get_pump_name", None) or getattr(pump, "get_device_name")
        return str(getter())

    def close(self) -> None:
        """Stop this pump, stop the bus, and release the Qmix connection."""
        errors = self._cleanup_bus(stop_pump=True)
        if errors:
            raise NemesysPumpError("Could not close neMESYS pump cleanly: " + "; ".join(errors))

    def __enter__(self) -> "NemesysPump":
        self.connect()
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None:
        self.close()

    def _load_sdk(self) -> None:
        if self._qmixbus is not None:
            return
        if not self.sdk_python_path.is_dir():
            raise NemesysPumpError(f"CETONI SDK Python directory does not exist: {self.sdk_python_path}")
        path = str(self.sdk_python_path)
        if path not in sys.path:
            sys.path.insert(0, path)
        try:
            from qmixsdk import qmixbus, qmixpump
        except Exception as exc:
            raise NemesysPumpError(
                f"Could not import the CETONI Qmix SDK from {self.sdk_python_path}"
            ) from exc
        self._qmixbus = qmixbus
        self._qmixpump = qmixpump

    def _ready_pump(self) -> Any:
        if not self.is_connected:
            raise NemesysPumpError("Pump is not connected; call connect() first")
        self._raise_if_faulted()
        return self._pump

    def _raise_if_faulted(self) -> None:
        if self._pump is not None and self._pump.is_in_fault_state():
            raise NemesysPumpError(
                "The neMESYS pump reports a fault during use. Automatic fault clearing "
                "is performed only while connecting; inspect QmixElements before reconnecting."
            )

    def _validate_flow_magnitude(self, flow: float) -> None:
        maximum = self.maximum_flow_ul_min
        if flow > maximum:
            raise ValueError(
                f"Requested flow magnitude {flow:g} uL/min exceeds the live pump limit "
                f"of {maximum:g} uL/min"
            )

    def _wait_until_idle_or(
        self,
        completion_check: Any,
        timeout_s: float,
        timeout_message: str,
    ) -> None:
        deadline = time.monotonic() + timeout_s
        while True:
            self._raise_if_faulted()
            if completion_check():
                return
            if time.monotonic() >= deadline:
                self.stop()
                raise NemesysPumpError(f"{timeout_message} after {timeout_s:g} seconds")
            time.sleep(self.poll_interval_s)

    def _cleanup_bus(self, *, stop_pump: bool) -> list[str]:
        errors: list[str] = []
        if stop_pump and self._pump is not None and self._bus_started:
            try:
                self._pump.stop_pumping()
            except Exception as exc:
                errors.append(f"stop pump: {exc}")
        if self._bus is not None and self._bus_started:
            try:
                self._bus.stop()
            except Exception as exc:
                errors.append(f"stop bus: {exc}")
        if self._bus is not None and self._bus_opened:
            try:
                self._bus.close()
            except Exception as exc:
                errors.append(f"close bus: {exc}")
        self._pump = None
        self._bus = None
        self._bus_started = False
        self._bus_opened = False
        return errors

    @staticmethod
    def _finite_number(value: float, name: str) -> float:
        number = float(value)
        if not math.isfinite(number):
            raise ValueError(f"{name} must be finite")
        return number

    @classmethod
    def _positive_number(cls, value: float, name: str) -> float:
        number = cls._finite_number(value, name)
        if number <= 0:
            raise ValueError(f"{name} must be greater than zero")
        return number
